{% set version = "5.2.1" %}

package:
  name: decorator
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/decorator/decorator-{{ version }}.tar.gz
  sha256: 65f266143752f734b0a7cc83c46f4618af75b8c5911b00ccb61d0ac9b6da0360

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - decorator

about:
  home: https://github.com/micheles/decorator
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: Decorators for Humans

extra:
  recipe-maintainers:
    - msarahan
    - pelson
    - ocefpaf
    - scopatz
