{% set version = "5.3.0" %}

package:
  name: decorator
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/decorator/decorator-{{ version }}.tar.gz
  sha256: 95fda3122972c847cf0ff7e0ce2829bf25136f2526b627b3da85b60ca5f485c0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - decorator

about:
  home: https://github.com/micheles/decorator
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: Decorators for Humans

extra:
  recipe-maintainers:
    - msarahan
    - pelson
    - ocefpaf
    - scopatz
