{% set version = "5.0.0" %}

package:
  name: decorator
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/decorator/decorator-{{ version }}.tar.gz
  sha256: 11f6e1e1ba3e7ffbfd9362da692e65791d6367bfd68ebf07064dd29a6e30f137

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - decorator

about:
  home: https://github.com/micheles/decorator
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Better living through Python with decorators.

extra:
  recipe-maintainers:
    - msarahan
    - pelson
    - ocefpaf
    - scopatz
