travis:
  secure:
    BINSTAR_TOKEN: iI+iicDhiLr5HrYtjuSUvdMeJDpUlbOM88HHkML5kPjy1+u2AyKSGjTNxIrWREhqULOCjqEThMyh+NlJTA5V5/5wG6lqPLGLMqIzARRdHIVm5EmOFsemc4sXyb28hBW73z1MbgtC+nK5kMRzm5UOyqIR5ACseo47H3J/zmr5Gtsi1ZwQgpzzy1UGVhVvA1RogKESvrnGw1vBNK+hqvdNFr/tQrGoXDHpqyy601LN47ufCLuwo83ciZseiRvKoWJHJleZCVRrn+uniQk6lzI/6B1At4paMSEEJ4NaicDJaS7Nseoljkid3/LH3GU6SGbTzX3gmh2HSWgDJ3w+dZYy5rzliHcnEeFRlTvBLRpNPnJpBOMZg6AiviMHo+5uUqeNLrOIsC3Y2yBT0pD1lBGuVKa0zglKvjsUZEbR5+NeFcFrPSaZsQkO/+ttv/gneqt9h49PTTaMqeET7J40Yyxgs6cvyWFjHEiJ5OAaPP0EJ2TaHgBcD9et8gwJz3sEJdCCxj5ssWIXTEQP5PmyPfLFGs9ePtXA7krr81yp5A6Fc5+qbEhly3Da4xndovAJEVUL2pPFI4m4Q680Y8taR3RWXLkXw2rOc0Q4x+pCb6pk2wv8MYrw//X0dhkQluaa2mYd3Zvqxx80I5QqP8N1jbqpJSntm8qUYWswv+Rwf6Jxfqk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
